spring:
#  数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/superblog?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#  配置
  jpa:
    show-sql: false
    open-in-view: false
#  redis配置

#  servlet配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 256MB
      max-request-size: 10GB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 8084

#  阿里云服务配置
aliyun:
  oss:
    bucketName: "test-cyc"
    endPoint: "oss-cn-beijing.aliyuncs.com"
    accessKeyId: "LTAI5tKrgVhpnarVn8gWdv8N"
    accessKeySecret: "5fOsLEiQ9B3timfaFznKtgsIT4jvf6"